# PC Cleaner - Application Config and Constants

import os
from pathlib import Path
from typing import Dict, List, Set

APP_NAME = "PC Cleaner"
APP_VERSION = "1.0.0"
APP_ORGANIZATION = "Antigravity Software"

# Category Identifiers
CAT_TEMP = "temp"
CAT_CACHE = "cache"
CAT_LOGS = "logs"
CAT_THUMBNAILS = "thumbnails"
CAT_BROWSER_CACHE = "browser_cache"
CAT_APP_CACHE = "app_cache"
CAT_RECYCLE_BIN = "recycle_bin"
CAT_LARGE_FILES = "large_files"

# All cleanable categories (large files are scanned separately and never auto-selected)
CLEANABLE_CATEGORIES = [
    CAT_TEMP,
    CAT_CACHE,
    CAT_LOGS,
    CAT_THUMBNAILS,
    CAT_BROWSER_CACHE,
    CAT_APP_CACHE,
]

# Large File Thresholds in Bytes
LARGE_FILE_THRESHOLDS = {
    "100 MB": 100 * 1024 * 1024,
    "500 MB": 500 * 1024 * 1024,
    "1 GB": 1 * 1024 * 1024 * 1024,
    "5 GB": 5 * 1024 * 1024 * 1024,
}

# Critical system directories that must NEVER be deleted or scanned for deletion
CRITICAL_SYSTEM_DIRS: Set[str] = {
    r"C:\Windows",
    r"C:\Windows\System32",
    r"C:\Windows\SysWOW64",
    r"C:\Windows\WinSxS",
    r"C:\Windows\Boot",
    r"C:\Windows\System",
    r"C:\Windows\system32\drivers",
    r"C:\Program Files\WindowsApps",
}

# Critical system files that must NEVER be deleted
PROTECTED_SYSTEM_FILES: Set[str] = {
    "pagefile.sys",
    "hiberfil.sys",
    "swapfile.sys",
    "bootmgr",
    "BOOTNXT",
    "ntldr",
    "NTDETECT.COM",
    "bootfont.bin",
}

# User personal folders that must NEVER be deleted automatically
PROTECTED_USER_FOLDERS: List[str] = [
    "Desktop",
    "Documents",
    "Pictures",
    "Music",
    "Videos",
    "Downloads",
    "OneDrive",
    "Contacts",
    "Searches",
    "Favorites",
    "Links",
    "Saved Games",
]

# Sensitive browser / app files that must NEVER be removed (logins, session, bookmarks, etc.)
PROTECTED_EXTENSIONS: Set[str] = {
    ".sqlite",
    ".sqlite-wal",
    ".sqlite-shm",
    ".db",  # except explicitly known thumbnail databases
    ".key",
    ".pem",
    ".crt",
    ".cert",
    ".pfx",
    ".p12",
}

# Dangerous sensitive file basenames in appdata that must never be touched
PROTECTED_FILENAMES: Set[str] = {
    "login data",
    "login data-journal",
    "cookies",
    "cookies-journal",
    "web data",
    "web data-journal",
    "history",
    "history-journal",
    "bookmarks",
    "favicons",
    "preferences",
    "secure preferences",
    "master.passwd",
    "passwd",
    "credentials",
    "accounts.json",
    "tokens.json",
    "places.sqlite",
    "key4.db",
    "cert9.db",
    "logins.json",
}

# Translations dictionary
TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "app_title": "PC Cleaner",
        "tagline": "Windows System Health & Storage Optimizer",
        "professional_edition": "Professional Edition",
        "dashboard": "Dashboard",
        "cleaner": "Cleaner",
        "large_files": "Large Files",
        "apps": "Apps",
        "storage": "Storage",
        "history": "Scan History",
        "duplicates": "Duplicate Files",
        "settings": "Settings",
        "status_protected": "● System Protected",
        "status_scanning": "● Scanning System...",
        "scan_pc": "Scan PC",
        "scanning": "Scanning...",
        "review_files": "Review Files",
        "clean_selected": "Clean Selected",
        "cleaning": "Cleaning...",
        "storage_title": "Storage",
        "potential_cleanup": "Potential Cleanup",
        "total": "Total",
        "used": "Used",
        "free": "Free",
        "free_suffix": "Free",
        "last_scan": "Last Scan",
        "files_found": "Files Found",
        "large_files_count": "Large Files",
        "temp_files_count": "Temp Files",
        "cache_files_count": "Cache Files",
        "never": "Never",
        "status_label": "Status",
        "cleanable_items": "Cleanable items",
        "ready_to_analyze": "Ready to analyze system for safe junk removal",
        "refresh_storage": "Refresh Storage",
        "empty_bin_btn": "Empty Bin",
        "empty_recycle_bin": "Empty Recycle Bin",
        "recycle_bin_warning": "This action cannot be easily undone. Are you sure you want to empty the Recycle Bin?",
        "recycle_bin_empty": "Recycle Bin is empty",
        "recycle_bin_title": "Recycle Bin",
        "category_temp": "Temporary Files",
        "category_cache": "System & App Cache",
        "category_logs": "Log Files",
        "category_thumbnails": "Thumbnails",
        "category_browser_cache": "Browser Cache",
        "category_app_cache": "Application Cache",
        "category_recycle_bin": "Recycle Bin",
        "files_selected": "Files selected",
        "space_to_free": "Space to free",
        "select_all": "Select All",
        "deselect_all": "Deselect All",
        "cleaner_subtitle": "Review detected files and safely clean selected categories",
        "confirm_clean_title": "Are you sure?",
        "confirm_clean_msg": "Do you want to permanently remove {count} selected files ({size})?\nThis action cannot be undone.",
        "clean_completed": "Cleanup Completed",
        "clean_completed_msg": "Successfully freed {freed_size}.\n{failed_count} files could not be removed.",
        "skipped_safety": "Skipped for safety",
        "in_use": "File currently in use",
        "access_denied": "Access denied / insufficient permissions",
        "large_files_subtitle": "Find space-hogging files. Large files are never automatically removed.",
        "scan_large_files": "Scan Large Files",
        "open_in_explorer": "Open in Explorer",
        "delete_selected": "Delete Selected",
        "apps_subtitle": "Inspect installed desktop programs and launch official uninstallers",
        "refresh_apps": "Refresh Apps",
        "apps_safety_notice": "🛡️ Safe Uninstaller: PC Cleaner invokes the software vendor's official uninstaller. It never deletes program files manually.",
        "storage_subtitle": "Inspect disk space consumption across top-level system directories",
        "storage_distribution": "Storage Distribution",
        "duplicates_subtitle": "Find files with identical content. Files will never be deleted automatically.",
        "find_duplicates": "Find Duplicates",
        "duplicates_note": "Duplicates are identified by SHA-256 hash. Files will never be deleted automatically.",
        "history_subtitle": "Local audit trail of previous scans and space optimizations",
        "history_date": "Date",
        "history_duration": "Duration",
        "history_found": "Found",
        "history_cleaned": "Cleaned",
        "clear_history": "Clear History",
        "no_history": "No scan history recorded yet.",
        "settings_subtitle": "Configure scan behavior, protection preferences, and appearance",
        "settings_general": "General",
        "confirm_before_clean": "Confirm before cleaning",
        "run_on_startup": "Run scan on startup",
        "start_minimized": "Start minimized",
        "settings_cleaning": "Default Cleaning Categories",
        "settings_appearance": "Appearance",
        "theme_dark": "Dark (Dark Mode)",
        "theme_light": "Light (Light Mode)",
        "settings_language": "Language",
        "save_settings": "Save Settings",
        "settings_saved": "Settings saved successfully",
        "search_placeholder": "Search files...",
        "filter_min_size": "Min size:",
        "path_header": "Location",
        "name_header": "Name",
        "size_header": "Size",
        "date_header": "Modified Date",
        "publisher_header": "Publisher",
        "version_header": "Version",
        "action_header": "Action",
        "uninstall_btn": "Uninstall",
        "storage_analyzer_title": "Storage Analyzer",
        "storage_note": "Visualizes disk usage across top-level folders on drive {drive}.",
        "select_drive": "Select Drive:",
        "analyze_drive": "Analyze Drive",
        "items_count": "{count} items",
        "files_count": "{count} files",
        "theme_label": "Theme:",
        "language_label": "Language:",
    },
    "de": {
        "app_title": "PC Cleaner",
        "tagline": "Windows Systemzustand & Speicheroptimierung",
        "professional_edition": "Professional Edition",
        "dashboard": "Dashboard",
        "cleaner": "Cleaner",
        "large_files": "Große Dateien",
        "apps": "Apps",
        "storage": "Storage",
        "history": "Scan-Historie",
        "duplicates": "Duplikate",
        "settings": "Einstellungen",
        "status_protected": "● System geschützt",
        "status_scanning": "● System wird gescannt...",
        "scan_pc": "PC scannen",
        "scanning": "Wird gescannt...",
        "review_files": "Dateien prüfen",
        "clean_selected": "Ausgewählte bereinigen",
        "cleaning": "Wird bereinigt...",
        "storage_title": "Speicherplatz",
        "potential_cleanup": "Potenziell bereinigbar",
        "total": "Gesamt",
        "used": "Belegt",
        "free": "Frei",
        "free_suffix": "Frei",
        "last_scan": "Letzter Scan",
        "files_found": "Gefundene Dateien",
        "large_files_count": "Große Dateien",
        "temp_files_count": "Temporäre Dateien",
        "cache_files_count": "Cache-Dateien",
        "never": "Nie",
        "status_label": "Status",
        "cleanable_items": "Bereinigbare Dateien",
        "ready_to_analyze": "Bereit zur Analyse für sichere Datenbereinigung",
        "refresh_storage": "Speicher aktualisieren",
        "empty_bin_btn": "Papierkorb leeren",
        "empty_recycle_bin": "Papierkorb leeren",
        "recycle_bin_warning": "Diese Aktion kann nicht rückgängig gemacht werden. Möchten Sie den Papierkorb wirklich leeren?",
        "recycle_bin_empty": "Papierkorb ist leer",
        "recycle_bin_title": "Papierkorb",
        "category_temp": "Temporäre Dateien",
        "category_cache": "System- & App-Cache",
        "category_logs": "Log-Dateien",
        "category_thumbnails": "Miniaturansichten (Thumbnails)",
        "category_browser_cache": "Browser-Cache",
        "category_app_cache": "Anwendungs-Cache",
        "category_recycle_bin": "Papierkorb",
        "files_selected": "Ausgewählte Dateien",
        "space_to_free": "Freizugebender Speicher",
        "select_all": "Alle auswählen",
        "deselect_all": "Alle abwählen",
        "cleaner_subtitle": "Erkannte Dateien prüfen und ausgewählte Kategorien sicher bereinigen",
        "confirm_clean_title": "Sind Sie sicher?",
        "confirm_clean_msg": "Möchten Sie {count} ausgewählte Dateien ({size}) wirklich endgültig entfernen?\nDieser Vorgang kann nicht rückgängig gemacht werden.",
        "clean_completed": "Bereinigung abgeschlossen",
        "clean_completed_msg": "Erfolgreich {freed_size} freigegeben.\n{failed_count} Dateien konnten nicht entfernt werden.",
        "skipped_safety": "Aus Sicherheitsgründen übersprungen",
        "in_use": "Datei wird gerade verwendet",
        "access_denied": "Zugriff verweigert / unzureichende Berechtigungen",
        "large_files_subtitle": "Große Speicherfresser finden. Große Dateien werden niemals automatisch entfernt.",
        "scan_large_files": "Große Dateien suchen",
        "open_in_explorer": "Im Explorer anzeigen",
        "delete_selected": "Ausgewählte löschen",
        "apps_subtitle": "Installierte Windows-Programme einsehen und offizielle Deinstallation starten",
        "refresh_apps": "Apps aktualisieren",
        "apps_safety_notice": "🛡️ Sicherer Deinstaller: PC Cleaner startet den offiziellen Deinstaller des Herstellers. Keine manuelle Ordnerlöschung.",
        "storage_subtitle": "Speicherverbrauch der obersten Verzeichnisse auf dem Laufwerk analysieren",
        "storage_distribution": "Speicherplatz-Verteilung",
        "duplicates_subtitle": "Inhaltsgleiche Dateien finden. Dateien werden niemals automatisch gelöscht.",
        "find_duplicates": "Duplikate suchen",
        "duplicates_note": "Duplikate werden über SHA-256 Hashes ermittelt. Keine Dateien werden automatisch gelöscht.",
        "history_subtitle": "Lokales Protokoll früherer Scans und Speicherbereinigungen",
        "history_date": "Datum",
        "history_duration": "Dauer",
        "history_found": "Gefunden",
        "history_cleaned": "Bereinigt",
        "clear_history": "Historie leeren",
        "no_history": "Bisher keine Scan-Historie vorhanden.",
        "settings_subtitle": "Scan-Verhalten, Schutzfunktionen und Design anpassen",
        "settings_general": "Allgemein",
        "confirm_before_clean": "Vor dem Löschen bestätigen",
        "run_on_startup": "Scan beim Systemstart ausführen",
        "start_minimized": "Minimiert starten",
        "settings_cleaning": "Standard-Bereinigungskategorien",
        "settings_appearance": "Erscheinungsbild",
        "theme_dark": "Dunkel (Dark Mode)",
        "theme_light": "Hell (Light Mode)",
        "settings_language": "Sprache",
        "save_settings": "Einstellungen speichern",
        "settings_saved": "Einstellungen erfolgreich gespeichert",
        "search_placeholder": "Dateien filtern...",
        "filter_min_size": "Mindestgröße:",
        "path_header": "Pfad",
        "name_header": "Dateiname",
        "size_header": "Größe",
        "date_header": "Änderungsdatum",
        "publisher_header": "Herausgeber",
        "version_header": "Version",
        "action_header": "Aktion",
        "uninstall_btn": "Deinstallieren",
        "storage_analyzer_title": "Speicherplatz-Analyse",
        "storage_note": "Visualisiert die Speicherbelegung der Verzeichnisse auf Laufwerk {drive}.",
        "select_drive": "Laufwerk wählen:",
        "analyze_drive": "Laufwerk analysieren",
        "items_count": "{count} Elemente",
        "files_count": "{count} Dateien",
        "theme_label": "Design:",
        "language_label": "Sprache:",
    },
}
